-- `account_schedulable_idx` serves no query, and never has.
--
-- Both 0001 and 0013 introduce it as "the scheduler's candidate query: by
-- provider, eligible only". No such query exists. What the scheduler actually
-- runs is `repo::candidates`:
--
--     FROM account a
--     JOIN account_route ar ON ar.account_id = a.id
--     WHERE ar.route_id = $1
--       AND a.provider = $2
--       AND (a.owner_principal_id IS NULL OR a.owner_principal_id = $3)
--
-- Three things about that make the index unusable for it. The driving filter is
-- `ar.route_id`, which `account_route_by_route_idx` already serves; the join
-- into `account` is by primary key, which is the cheapest access there is; and
-- the query has no `schedulable` predicate at all — eligibility is decided in
-- memory over the loaded candidates, deliberately, because the scheduler needs
-- the ineligible rows to explain why a request could not be served. A partial
-- index whose predicate the query does not state cannot be chosen for it.
--
-- Two queries do filter `schedulable`, and this index can serve neither.
--
-- The seat poller runs `WHERE kind = 'oauth' AND schedulable`, and
-- `repo::route_channels` — which answers "what can this route offer" — runs
-- `WHERE ar.route_id = $1 AND a.schedulable AND (...)`. Both match the
-- index's predicate and neither constrains `provider`, which is the index's
-- leading column. A B-tree cannot be range-scanned on its second column
-- without a bound on its first, so both fall back to the same access they
-- already use.
--
-- (An earlier draft of this comment claimed the poller was the only such
-- query. It was not, and the claim was load-bearing: if a `schedulable` query
-- DID lead with `provider`, dropping this index would be a regression rather
-- than a saving. `an_index_on_provider_cannot_serve_a_query_without_one` in
-- `repo.rs` now settles that by asking the planner instead of by argument.)
--
-- So it has only ever cost. 0013 removed `last_used_at` from it precisely
-- because index maintenance on this table is write cost for no reader — every
-- insert and every update to `provider`, `priority` or `schedulable` maintains
-- it, on a small, hot table where a sequential scan of a few hundred rows is
-- cheaper than the index would be even if a query named it. That argument does
-- not stop at one column.
--
-- Dropping it rather than retargeting it, for the same reason: there is no
-- query to retarget it at. If one appears — a deployment with enough
-- credentials that `candidates` needs help — the index that would serve it is
-- on `account_route (route_id, account_id)` or on `account (provider)`, and it
-- should be added then, against a plan, rather than guessed at now.
--
-- `account_owner_idx` stays. It is partial on `owner_principal_id IS NOT NULL`,
-- which is a genuinely selective predicate on a column `candidates` does filter.

DROP INDEX IF EXISTS account_schedulable_idx;
