#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8
TOTAL_MINUTES=25

# Where the terraform stack lives, and where captured values are kept. Values
# are stored as TF_VAR_* so `source`ing the file hands them straight to
# terraform. The file holds secrets (KEK, DB URL) — it stays on this machine and
# is gitignored; never commit it.
STACK_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/stacks/gcp-cloudrun" && pwd)"
ENV_FILE="$(dirname "${BASH_SOURCE[0]}")/gcp-deploy.local.env"
TF="$(command -v tofu || command -v terraform || true)"

require() { command -v "$1" >/dev/null 2>&1 || { warn "missing '$1' — install it and re-run"; MISSING=1; }; }

banner "Deploy open-ai-gateway to GCP Cloud Run"

# ── 1. Tools and sign-in ──────────────────────────────────────────────────
stage "Prerequisites and GCP sign-in" 4
say "Checking the tools this deploy needs, then signing you in to GCP."
MISSING=0
require gcloud; require openssl; [ -n "$TF" ] || { warn "missing 'tofu' or 'terraform'"; MISSING=1; }
(( MISSING )) && { warn "install the missing tools above, then re-run."; exit 1; }
say "Signing in (a browser window will open for each — skip if already done):"
step "Your Google account, for gcloud itself."
confirm "Run 'gcloud auth login' now?" && gcloud auth login || note "skipped — assuming you're already signed in"
step "Application-default credentials, which terraform uses."
confirm "Run 'gcloud auth application-default login' now?" && gcloud auth application-default login || note "skipped"

# ── 2. Project and region ─────────────────────────────────────────────────
stage "Project and region" 3
say "Which GCP project and region this gateway lands in."
open_url "https://console.cloud.google.com/projectselector2/home/dashboard"
step "Pick or create a project; copy its Project ID (not the name)."
ask GCP_PROJECT_ID "Project ID:"
ask GCP_REGION "Region [Enter for us-central1]:"; [ -z "$GCP_REGION" ] && GCP_REGION="us-central1"
gcloud config set project "$GCP_PROJECT_ID" >/dev/null 2>&1 || warn "couldn't set project; check the ID"
write_env TF_VAR_project_id "$GCP_PROJECT_ID"
write_env TF_VAR_region "$GCP_REGION"

# ── 3. Enable the APIs ────────────────────────────────────────────────────
stage "Enable the required GCP APIs" 3
say "Cloud Run, Secret Manager, and IAM at minimum; the managed data tier adds more."
step "Enabling core APIs (idempotent — safe to re-run)…"
gcloud services enable run.googleapis.com secretmanager.googleapis.com \
  iam.googleapis.com --project "$GCP_PROJECT_ID" \
  && say "core APIs enabled" || warn "some API enables failed; check billing is on"

# ── 4. Data tier ──────────────────────────────────────────────────────────
stage "Data tier — Postgres and Redis" 5
say "The credential store and the coordination cache. Two options:"
note "  managed — Cloud SQL + Memorystore, private, pins you to GCP (needs a VPC)."
note "  neutral — you supply Neon + Upstash URLs; portable across clouds. Simplest to start."
if confirm "Use the neutral tier (recommended to start)?"; then
  write_env TF_VAR_data_mode "neutral"
  open_url "https://console.neon.tech/"
  step "Create a Postgres DB. Copy the POOLED connection string (host contains '-pooler')."
  warn "It must include ?sslmode=require — this connection carries the credential store."
  ask_secret NEUTRAL_DB "Neon pooled database URL:"
  open_url "https://console.upstash.com/"
  step "Create a Redis DB. Copy the rediss:// URL (TLS)."
  ask_secret NEUTRAL_REDIS "Upstash redis URL:"
  write_env TF_VAR_neutral_database_url "$NEUTRAL_DB"
  write_env TF_VAR_neutral_redis_url "$NEUTRAL_REDIS"
  gcloud services enable >/dev/null 2>&1 || true
else
  write_env TF_VAR_data_mode "managed"
  say "Enabling Cloud SQL, Memorystore, and networking APIs…"
  gcloud services enable sqladmin.googleapis.com redis.googleapis.com \
    compute.googleapis.com servicenetworking.googleapis.com vpcaccess.googleapis.com \
    --project "$GCP_PROJECT_ID" || warn "some enables failed"
  step "Managed mode needs a VPC network and a subnet for Direct VPC egress."
  ask TF_NETWORK "VPC network id (projects/<p>/global/networks/<n>):"
  ask TF_SUBNET  "VPC subnet id (projects/<p>/regions/<r>/subnetworks/<s>):"
  write_env TF_VAR_network_id "$TF_NETWORK"
  write_env TF_VAR_vpc_subnet "$TF_SUBNET"
fi

# ── 5. Gateway secrets ────────────────────────────────────────────────────
stage "Gateway secrets" 2
say "The signing secret and the credential-encryption key. Generated here, then"
say "stored in GCP Secret Manager by the deploy — never printed to a dashboard."
SIGNING="$(_existing TF_VAR_signing_secret || openssl rand -base64 48 | tr -d '\n')"
KEK="$(_existing TF_VAR_credential_kek || openssl rand -base64 32 | tr -d '\n')"
write_env TF_VAR_signing_secret "$SIGNING"
write_env TF_VAR_credential_kek "$KEK"
say "generated (or kept from a previous run)."

# ── 6. Container image ────────────────────────────────────────────────────
stage "Container image" 1
say "Which image Cloud Run runs. The published multi-arch image is public and"
say "pullable straight from Cloud Run; press Enter to use it."
ask GATEWAY_IMAGE "Image [Enter for ghcr.io/hexuria/open-ai-gateway:main]:"
[ -z "$GATEWAY_IMAGE" ] && GATEWAY_IMAGE="ghcr.io/hexuria/open-ai-gateway:main"
write_env TF_VAR_image "$GATEWAY_IMAGE"

# ── 7. Edge (optional Cloudflare) ─────────────────────────────────────────
stage "Public edge (optional)" 2
say "Cloud Run gives you a *.run.app URL out of the box. A Cloudflare zone adds"
say "your own hostname and tuned streaming timeouts. Skip to use the run.app URL."
if confirm "Put a Cloudflare hostname in front?"; then
  ask CF_ZONE "Cloudflare zone id:"
  ask CF_HOST "Hostname (e.g. gateway.example.com):"
  ask_secret CF_TOKEN "Cloudflare API token (Zone:DNS + Zone:Ruleset edit):"
  write_env TF_VAR_cloudflare_zone_id "$CF_ZONE"
  write_env TF_VAR_hostname "$CF_HOST"
  write_env CLOUDFLARE_API_TOKEN "$CF_TOKEN"
else
  write_env TF_VAR_cloudflare_zone_id ""
fi

# ── 8. Deploy ─────────────────────────────────────────────────────────────
stage "Deploy" 5
say "Everything is captured. This runs 'terraform apply' against your project:"
note "  it creates Secret Manager entries, a service account, and the Cloud Run"
note "  service + a one-shot migration job, then (if set) the Cloudflare records."
warn "This provisions real, billable GCP resources."
if confirm "Apply now?"; then
  set -a; # shellcheck disable=SC1090
  . "$ENV_FILE"; set +a
  ( cd "$STACK_DIR" && "$TF" init -input=false && "$TF" apply -input=false ) || {
    warn "apply failed — read the error above; re-run this wizard to retry (values are kept)."; exit 1; }
  say "Fetching the service URL…"
  URL="$(cd "$STACK_DIR" && { "$TF" output -raw public_url 2>/dev/null || "$TF" output -raw gateway_url 2>/dev/null; } || true)"
  [ -n "$URL" ] && say "Gateway URL: ${BOLD}${URL}${RESET}"
  step "Bootstrap the first admin key against the deployed gateway:"
  note "  the migration job already ran the schema. Create a principal + key with"
  note "  'oag admin init' pointed at the deployed DB, or via a one-off Cloud Run job."
else
  note "not applied. Re-run this wizard when ready — your answers are saved in $ENV_FILE."
fi

finish
